{% set python_min = '3.10.0' %}
{% set name = "jupyterlab-s3-browser" %}
{% set version = "0.12.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/jupyterlab_s3_browser-{{ version }}.tar.gz
  sha256: 14eabbd562f26f1267a3b176f9d2c26f782f61267330bd1dab0504d2494f37b4

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 2

requirements:
  host:
    - python {{ python_min }}
    - jupyter_packaging >=0.7.9
    - jupyterlab >=3.0,<4.0
    - setuptools >=40.8.0
    - wheel
    - poetry-core
    - pip
  run:
    - python >={{ python_min }}
    - jupyterlab >=2.0.0 # https://github.com/IBM/jupyterlab-s3-browser/blob/0.12.0/setup.py#L100
    - notebook
    - boto3
    - s3fs >=2021.10.1
    - jupyter_server
    - singleton-decorator

test:
  imports:
    - jupyterlab_s3_browser
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/IBM/jupyterlab-s3-browser
  summary: JupyterLab extension for browsing S3-compatible object storage
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
